### ISSUE TITLE
Xcode 11.4 and AudioKit v4.9.4/v5.0.b1

### ISSUE THREAD

**Issue by kurteran** [AudioKit/AudioKit#1993]
Hi,
I've updated Xcode to v11.4, I'm using AudioKit v4.9.4 which has no problem in Xcode 11.3.1,
now after I've updated it, I've got errors like in issue: https://github.com/AudioKit/AudioKit/issues/1987

I took megastep's advice to update AudioKit to v5.0.b1,
which by the way can't be updated it Cocoapods:

<img width="525" alt="Screen Shot 2020-03-25 at 19 44 18" src="https://user-images.githubusercontent.com/46021998/77568279-105d6d80-6ed1-11ea-8444-c54c177a857a.png">

Had to update Cocoapods to 1.9.1 (If you try to downgrade to install through macOS Software Cocoapods v1.5.2, you have to clean pod and reinstall CocoaPods again), to install AudioKit v5.0.b1 at the terminal.

Cleaned build folder and re-build project, 
**renamed AudioKit to AKManager**,
got no errors like in v4.9.4,
besides Swift Compiler Warning: "Passing 'String' to parameter, but argument 'path' should be a pointer that outlives the call to 'init(sampleDescriptor:path:)'" At AKSampler Init(): loadCompressedSampleFile(from: , path:)

fixed it by:

> sampler.loadCompressedSampleFile(from: AKSampleFileDescriptor(sampleDescriptor: sd, path: fileURL.path))

->

> let string = (fileURL.path as NSString).utf8String
>         let buffer = UnsafeMutablePointer<Int8>(mutating: string)
>         sampler.loadCompressedSampleFile(from: AKSampleFileDescriptor(sampleDescriptor: sd, path: buffer))

I thought it was it! 
But then, after running my project, I got into my recording view controller which connected to the conductor class and all samplers and effects inside of it, then the app crashed:

<img width="848" alt="Screen Shot 2020-03-25 at 20 12 49" src="https://user-images.githubusercontent.com/46021998/77570865-181f1100-6ed5-11ea-8b15-2e085ad9ed1e.png">

I've tried to comment all of the related AKSamplers, but then I got the same error for AKDelay:
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

Xcode 11.4 with AudioKit 4.9.4:
<img width="256" alt="Screen Shot 2020-03-25 at 19 41 27" src="https://user-images.githubusercontent.com/46021998/77568026-aa70e600-6ed0-11ea-84e4-4d222b0352da.png">

**Comment by christianhengst** [comment]
Hi! I've got a similar issue with AKSampler.

I've managed to build my Xcode 11.4 project using pod version "v5.0.b1". 
But when `AKSampler()` is used the app crashes with this log:

```
Fatal error: Use of unimplemented initializer 'init()' for class 'AudioKit.AKSampler'
```

Any suggestions?

**Comment by megastep** [comment]
@christianhengst this is a different issue though and version 5.0 is still in beta; it looks like we need to add a missing method that is needed by the swift interface files.

**Comment by SwiftyFlow** [comment]
Same here, 2656 build errors... 

So happy that my boss keeps auto-update turned on and every single xCode update we run into the same issue. Well usually we don't get 2656 issues...

What do we do now? 

xCode: Version 11.4

Pods:
AudioKit: with or without ~> 4.0 
even AudioKit/Core has the same errors

**Comment by christianhengst** [comment]
@megastep Ok, sorry for mixing this up but I'm also getting the same issue when downgrading back to version "4.9.4". Before Xcode 11.4 was released I've had linked the framework manually. Since 11.4 I'm using the CocoaPod but now I'm facing this issue. Sure it is not related to the latest Xcode version?

**Comment by megastep** [comment]
I think the plan is to release 4.9.5 very soon, which will be built with 11.4 and should work as before. Meanwhile we'll keep working on 5.0 which is obviously not ready for public consumption just yet...

**Comment by megastep** [comment]
I just pushed 4.9.5 to CocoaPods, let me know if this fixes these issues for now.

**Comment by SwiftyFlow** [comment]
it's getting: Installing AudioKit (4.9.4)
and with '~> 4.9.5' it says it does not exist.
Is there a processing time to get there?

**Comment by megastep** [comment]
I believe there is a little bit of a delay indeed, however it should be available now. It just showed up when I did a `pod update` on a project of mine.

**Comment by SwiftyFlow** [comment]
Yes it is now (good to know)
It still has 2600 errors however as I don't need UI AudioKit/Core seems to work. I still can't run due to other pods but at least not AudioKit. Thanks for your reactiveness! Amazed 🤩

**Comment by christianhengst** [comment]
@megastep I still get the same issue  😔 Is it possible to provide the "4.9.5" build with Xcode 11.4 as framework on this page: https://audiokit.io/downloads/ 

Thank you!

**Comment by aure** [comment]
I just updated the downloads page with 4.9.5
